# permissions for end users to view cameras.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: camera-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-iot
    app.kubernetes.io/part-of: operator-iot
    app.kubernetes.io/managed-by: kustomize
  name: camera-viewer-role
rules:
- apiGroups:
  - mygroup.iot.com
  resources:
  - cameras
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mygroup.iot.com
  resources:
  - cameras/status
  verbs:
  - get
