# permissions for end users to view sensors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sensor-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-iot
    app.kubernetes.io/part-of: operator-iot
    app.kubernetes.io/managed-by: kustomize
  name: sensor-viewer-role
rules:
- apiGroups:
  - mygroup.iot.com
  resources:
  - sensors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mygroup.iot.com
  resources:
  - sensors/status
  verbs:
  - get
