apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: operator-iot.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Camera is the Schema for the cameras API
      displayName: Camera
      kind: Camera
      name: cameras.mygroup.iot.com
      statusDescriptors:
      - description: 'Represents the observations of a Camera''s current state. Camera.status.conditions.type
          are: "Available", "Progressing", and "Degraded" Camera.status.conditions.status
          are one of True, False, Unknown. Conditions store the status conditions
          of the Camera instances'
        displayName: Conditions
        path: conditions
      version: v1alpha1
    - description: Sensor is the Schema for the sensors API
      displayName: Sensor
      kind: Sensor
      name: sensors.mygroup.iot.com
      statusDescriptors:
      - description: 'Represents the observations of a Sensor''s current state. Sensor.status.conditions.type
          are: "Available", "Progressing", and "Degraded" Sensor.status.conditions.status
          are one of True, False, Unknown. Conditions store the status conditions
          of the Sensor instances'
        displayName: Conditions
        path: conditions
      version: v1alpha1
  description: demo operator
  displayName: iot-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - operator
  - kubernetes
  links:
  - name: Operator Iot
    url: https://operator-iot.domain
  maturity: alpha
  provider:
    name: iot-operator
  version: 0.0.0
